######################################################################
# Automatically generated by qmake (2.01a) Sat May 17 13:56:36 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += apex.h area.h mainwindow.h point.h side.h triangle.h trpoints.h
FORMS += mainwindow.ui
SOURCES += apex.cpp main.cpp mainwindow.cpp side.cpp triangle.cpp trpoints.cpp
