######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 3 23:45:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h triangle.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp triangle.cpp
