######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 12 17:49:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += area.h calcpoints.h mainwindow.h triangle.h
FORMS += mainwindow.ui
SOURCES += calcpoints.cpp main.cpp mainwindow.cpp triangle.cpp
